name: Deploy

on:
  push:
    branches:
      - main
      - incomes

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy files
        run: |
          # Constants
          S3_BUCKET=palm-lambda-code
          S3_KEY=lambda_code.zip
          LAMBDA_FUNCTION_NAME=palmPersonalFinanceLambda

          # zip current code
          zip -r updated_lambda.zip .

          # Upload the updated zip to S3
          aws s3 cp updated_lambda.zip s3://$S3_BUCKET/$S3_KEY

          # Update Lambda function code
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY

          # Cleanup
          rm updated_lambda.zip
